apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lwhsyemu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lwhsyemu:d7eaa229bc53ce66670acf99c6571eb0e2fc0668@sha256:bfb249c57bce73ec325d1f41f2c68166e7f981a8a178e18f7c35ddf918393a82
          name: container-image
